# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['nanite.py'],
             pathex=['./Project-Nanite', './Project-Nanite/venv/lib/python3.9/site-packages', './Project-Nanite/database', './Project-Nanite/file_access', './Project-Nanite/front_end', './Project-Nanite'],
             binaries=[],
             datas=[('nanite.ico', '.'),
                ('database/db.txt', './database'),
                ('file_access/file_access_ui/file_access.html','./file_access/file_acces_ui'),
                ('front_end/favicon.ico', './front_end'),
                ('front_end/templates/base.html', './front_end/templates'),
                ('front_end/templates/bodyopen-nosidebar.html', './front_end/templates'),
                ('front_end/templates/bodyopen-sidebar.html', './front_end/templates'),
                ('front_end/templates/charts.html', './front_end/templates'),
                ('front_end/templates/home.html', './front_end/templates'),
                ('front_end/templates/modal.html', './front_end/templates'),
                ('front_end/templates/projects.html', './front_end/templates'),
                ('front_end/templates/sidebar-info-list.html', './front_end/templates'),
                ('front_end/templates/stats-single.html', './front_end/templates'),
                ('front_end/templates/stats.html', './front_end/templates'),
                ('front_end/templates/welcome.html', './front_end/templates'),
                ('front_end/static/css/colors.css', './front_end/static/css'),
                ('front_end/static/css/colors.less', './front_end/static/css'),
                ('front_end/static/css/debug_style.css', './front_end/static/css'),
                ('front_end/static/css/explanation-on-hover.css', './front_end/static/css'),
                ('front_end/static/css/meyer-reset.css', './front_end/static/css'),
                ('front_end/static/css/proj-form.css', './front_end/static/css'),
                ('front_end/static/css/sanitize.css', './front_end/static/css'),
                ('front_end/static/css/stats-modal.css', './front_end/static/css'),
                ('front_end/static/css/style.css', './front_end/static/css'),
                ('front_end/static/css/style.less', './front_end/static/css'),
                ('front_end/static/imgs/creative_process_.svg', './front_end/static/imgs'),
                ('front_end/static/imgs/data_analysis_.svg', './front_end/static/imgs'),
                ('front_end/static/imgs/innovation_.svg', './front_end/static/imgs'),
                ('front_end/static/imgs/instruction_img.png', './front_end/static/imgs'),
                ('front_end/static/imgs/nanite-icon.svg', './front_end/static/imgs'),
                ('front_end/static/imgs/new-user.png', './front_end/static/imgs'),
                ('front_end/static/imgs/icons/add-circle.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/bell--v2.png', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/bell.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/download.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/green-tick.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/home.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/logout.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/nanite-outline-web.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/pencil.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/settings.png', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/settings.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/trash.svg', './front_end/static/imgs/icons'),
                ('front_end/static/imgs/icons/svg_work/logo-dummy_v3_web.svg', './front_end/static/imgs/icons/svg_work'),
                ('front_end/static/imgs/icons/svg_work/logo-dummy_v3.svg', './front_end/static/imgs/icons/svg_work'),
                ('front_end/static/imgs/icons/svg_work/logo-dummy.svg', './front_end/static/imgs/icons/svg_work'),
                ('front_end/static/imgs/icons/svg_work/logo-dummy_v3_web.svg', './front_end/static/imgs/icons/svg_work'),
                ('front_end/static/js/d3/d3.js', './front_end/static/js/d3'),
                ('front_end/static/js/d3/LICENSE', './front_end/static/js/d3'),
                ('front_end/static/js/body-scripts.js', './front_end/static/js'),
                ('front_end/static/js/head-scripts.js', './front_end/static/js'),
                ('front_end/static/js/project-modals.js', './front_end/static/js'),
                ('front_end/static/js/setup.js', './front_end/static/js'),
                ('front_end/static/js/stats-modal.js', './front_end/static/js'),
                ('front_end/static/js/viewport-scripts.js', './front_end/static/js')
                ],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='nanite',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='nanite.ico')
app = BUNDLE(exe,
             name='nanite.app',
             icon='nanite.ico',
             bundle_identifier=None)
